-- =============================================================================
-- 0035_categories_tree.sql
-- Árbol canónico de categorías: 25 raíces y 182 hijas.
--
-- Por qué. El árbol anterior se perdió al reconstruir las relaciones, y las
-- tiendas publican más de 3.000 nombres de categoría distintos que en el
-- fondo son unas 207 cosas. Este árbol cubre todos los rubros que hoy se
-- rastrean (supermercado, hogar, tecnología, ferretería, farmacia, moda,
-- juguetería, papelería...) con dos niveles: raíz y hija, que es lo que
-- admite el filtro del catálogo (0024). Es el que ve el usuario final al
-- navegar y filtrar.
--
-- Los slugs del árbol anterior que ya tenían contenido SEO en
-- src/db/seeds/category-content se conservan tal cual (136 de 144); los 71
-- nodos nuevos tienen su contenido en los archivos 18 a 24 de esa carpeta.
-- Después de correr esto: `node scripts/seed-category-content.mjs`.
--
-- Origen. Generado por src/db/seeds/categories/build.mjs desde tree.tsv.
-- Para cambiar un nombre o agregar un nodo: editar el TSV y regenerar, no
-- este archivo.
--
-- Idempotente: inserta por slug; si el slug ya existe actualiza nombre,
-- descripción, padre, path, nivel y posición, y no toca imagen ni destacado.
-- =============================================================================

with nodes (slug, parent_slug, name, description, path, level, position) as (
  values
    ('abarrotes', null, 'Abarrotes', 'Despensa: granos, aceites, enlatados, pastas, cereales, snacks, panadería y congelados.', 'abarrotes', 0, 0),
    ('arroz-frijoles-semillas', 'abarrotes', 'Arroz, Frijoles y Semillas', 'Arroz, frijoles, lentejas, granos básicos y semillas.', 'abarrotes/arroz-frijoles-semillas', 1, 0),
    ('aceites-mantecas-aderezos', 'abarrotes', 'Aceites, Mantecas y Aderezos', 'Aceites de cocina, mantecas, mayonesa, aderezos y vinagres.', 'abarrotes/aceites-mantecas-aderezos', 1, 1),
    ('enlatados-conservas', 'abarrotes', 'Enlatados y Conservas', 'Atún, vegetales y frutas enlatadas, aceitunas y conservas.', 'abarrotes/enlatados-conservas', 1, 2),
    ('pastas-salsas', 'abarrotes', 'Pastas y Salsas', 'Pastas, salsas para pasta y pizza, cátsup, mostaza y salsas picantes.', 'abarrotes/pastas-salsas', 1, 3),
    ('sopas-cremas-instantaneos', 'abarrotes', 'Sopas, Cremas e Instantáneos', 'Sopas, consomés, cremas y comida instantánea.', 'abarrotes/sopas-cremas-instantaneos', 1, 4),
    ('harinas-mezclas-reposteria', 'abarrotes', 'Harinas, Mezclas y Repostería', 'Harinas, mezclas para hornear, gelatinas, flanes y chocolate para hornear.', 'abarrotes/harinas-mezclas-reposteria', 1, 5),
    ('cereales-avenas-barras', 'abarrotes', 'Cereales, Avenas y Barras', 'Cereales, avenas, granolas, barras, mermeladas, miel y untables.', 'abarrotes/cereales-avenas-barras', 1, 6),
    ('cafe-te-modificadores', 'abarrotes', 'Café, Té y Modificadores', 'Café, té, infusiones, cremas para café y jarabes.', 'abarrotes/cafe-te-modificadores', 1, 7),
    ('azucar-endulzantes-especias', 'abarrotes', 'Azúcar, Endulzantes y Especias', 'Azúcar, sustitutos, sal, especias, sazonadores y condimentos.', 'abarrotes/azucar-endulzantes-especias', 1, 8),
    ('snacks-botanas-galletas', 'abarrotes', 'Snacks, Botanas y Galletas', 'Frituras, palomitas, galletas, frutos secos y nueces.', 'abarrotes/snacks-botanas-galletas', 1, 9),
    ('dulces-chocolates', 'abarrotes', 'Dulces y Chocolates', 'Chocolates, caramelos, gomitas, chicles y confites.', 'abarrotes/dulces-chocolates', 1, 10),
    ('panaderia-reposteria', 'abarrotes', 'Panadería y Repostería', 'Pan, tortillas, pasteles, donas y postres.', 'abarrotes/panaderia-reposteria', 1, 11),
    ('congelados', 'abarrotes', 'Congelados', 'Comida congelada, helados y postres congelados.', 'abarrotes/congelados', 1, 12),
    ('comidas-preparadas', 'abarrotes', 'Comidas Preparadas', 'Listo para comer, delicatessen, ensaladas y empacados.', 'abarrotes/comidas-preparadas', 1, 13),
    ('tabaco', 'abarrotes', 'Tabaco y Encendedores', 'Cigarros, tabacos, vapeo, fósforos y encendedores.', 'abarrotes/tabaco', 1, 14),
    ('lacteos-y-huevos', null, 'Lácteos y Huevos', 'Leche, quesos, yogurt, mantequilla y huevos.', 'lacteos-y-huevos', 0, 1),
    ('leche-liquida-polvo', 'lacteos-y-huevos', 'Leche Líquida y en Polvo', 'Leche entera, deslactosada, evaporada, condensada y bebidas vegetales.', 'lacteos-y-huevos/leche-liquida-polvo', 1, 0),
    ('quesos-cremas', 'lacteos-y-huevos', 'Quesos y Cremas', 'Quesos frescos, procesados, crema y natilla.', 'lacteos-y-huevos/quesos-cremas', 1, 1),
    ('yogurt-postres-lacteos', 'lacteos-y-huevos', 'Yogurt y Postres Lácteos', 'Yogurt batido, bebible, natural y postres.', 'lacteos-y-huevos/yogurt-postres-lacteos', 1, 2),
    ('mantequilla-margarina', 'lacteos-y-huevos', 'Mantequilla y Margarina', 'Mantequillas y margarinas.', 'lacteos-y-huevos/mantequilla-margarina', 1, 3),
    ('huevos', 'lacteos-y-huevos', 'Huevos', 'Cartones de huevos blancos y rojos.', 'lacteos-y-huevos/huevos', 1, 4),
    ('carnes-pescados-embutidos', null, 'Carnes, Pescados y Embutidos', 'Res, cerdo, pollo, embutidos y mariscos.', 'carnes-pescados-embutidos', 0, 2),
    ('carne-de-res', 'carnes-pescados-embutidos', 'Carne de Res', 'Cortes, molida, filetes y marinados de res.', 'carnes-pescados-embutidos/carne-de-res', 1, 0),
    ('carne-de-cerdo', 'carnes-pescados-embutidos', 'Carne de Cerdo', 'Chuletas, costilla, postas y marinados de cerdo.', 'carnes-pescados-embutidos/carne-de-cerdo', 1, 1),
    ('pollo-y-aves', 'carnes-pescados-embutidos', 'Pollo y Aves', 'Pollo entero, piezas, pechuga y pavo.', 'carnes-pescados-embutidos/pollo-y-aves', 1, 2),
    ('embutidos-jamones', 'carnes-pescados-embutidos', 'Embutidos y Jamones', 'Jamón, salchichas, chorizo, tocino y carnes frías.', 'carnes-pescados-embutidos/embutidos-jamones', 1, 3),
    ('pescados-mariscos', 'carnes-pescados-embutidos', 'Pescados y Mariscos', 'Pescado, camarones y mariscos frescos, congelados y enlatados.', 'carnes-pescados-embutidos/pescados-mariscos', 1, 4),
    ('frutas-y-verduras', null, 'Frutas y Verduras', 'Frescas, congeladas y empacadas.', 'frutas-y-verduras', 0, 3),
    ('frutas-frescas', 'frutas-y-verduras', 'Frutas Frescas', 'Bananos, manzanas, cítricos, berries y tropicales.', 'frutas-y-verduras/frutas-frescas', 1, 0),
    ('verduras-hortalizas', 'frutas-y-verduras', 'Verduras y Hortalizas', 'Tomate, cebolla, papa, lechuga, chiles y tubérculos.', 'frutas-y-verduras/verduras-hortalizas', 1, 1),
    ('hierbas-aromaticas', 'frutas-y-verduras', 'Hierbas Aromáticas', 'Cilantro, perejil, cebollino y hierbas frescas.', 'frutas-y-verduras/hierbas-aromaticas', 1, 2),
    ('ensaladas-empacadas', 'frutas-y-verduras', 'Ensaladas y Empacados', 'Ensaladas listas, vegetales procesados y congelados.', 'frutas-y-verduras/ensaladas-empacadas', 1, 3),
    ('jugos-y-bebidas', null, 'Jugos y Bebidas', 'Agua, jugos, gaseosas, energizantes y bebidas en polvo.', 'jugos-y-bebidas', 0, 4),
    ('aguas-purificadas-saborizadas', 'jugos-y-bebidas', 'Aguas Purificadas y Saborizadas', 'Agua natural, saborizada y envases.', 'jugos-y-bebidas/aguas-purificadas-saborizadas', 1, 0),
    ('gaseosas-refrescos', 'jugos-y-bebidas', 'Gaseosas y Refrescos', 'Carbonatados, refrescos y bebidas en polvo.', 'jugos-y-bebidas/gaseosas-refrescos', 1, 1),
    ('jugos-nectares', 'jugos-y-bebidas', 'Jugos y Néctares', 'Jugos de fruta, néctares y jugos de verduras.', 'jugos-y-bebidas/jugos-nectares', 1, 2),
    ('bebidas-energeticas-isotonicas', 'jugos-y-bebidas', 'Bebidas Energéticas e Isotónicas', 'Energizantes, hidratantes y bebidas deportivas.', 'jugos-y-bebidas/bebidas-energeticas-isotonicas', 1, 3),
    ('te-frio-bebidas-preparadas', 'jugos-y-bebidas', 'Té Frío y Bebidas Preparadas', 'Té listo para beber, café preparado y bebidas frías.', 'jugos-y-bebidas/te-frio-bebidas-preparadas', 1, 4),
    ('cervezas-vinos-licores', null, 'Cervezas, Vinos y Licores', 'Cerveza, vino y destilados.', 'cervezas-vinos-licores', 0, 5),
    ('cervezas', 'cervezas-vinos-licores', 'Cervezas', 'Cervezas nacionales, importadas y artesanales.', 'cervezas-vinos-licores/cervezas', 1, 0),
    ('vinos', 'cervezas-vinos-licores', 'Vinos', 'Tinto, blanco, rosado, espumante y sidras.', 'cervezas-vinos-licores/vinos', 1, 1),
    ('ron-tequila-aguardiente', 'cervezas-vinos-licores', 'Ron, Tequila y Aguardiente', 'Ron, tequila, brandy y aguardientes.', 'cervezas-vinos-licores/ron-tequila-aguardiente', 1, 2),
    ('whisky-vodka-ginebra', 'cervezas-vinos-licores', 'Whisky, Vodka y Ginebra', 'Whisky, vodka, gin y otros destilados.', 'cervezas-vinos-licores/whisky-vodka-ginebra', 1, 3),
    ('hielo-mezcladores', 'cervezas-vinos-licores', 'Hielo y Mezcladores', 'Hielo, mixers y mezcladores.', 'cervezas-vinos-licores/hielo-mezcladores', 1, 4),
    ('limpieza-del-hogar', null, 'Limpieza del Hogar', 'Limpiadores, lavandería, papel y utensilios de limpieza.', 'limpieza-del-hogar', 0, 6),
    ('detergentes-suavizantes', 'limpieza-del-hogar', 'Detergentes y Suavizantes', 'Detergentes, suavizantes, quitamanchas y accesorios de lavandería.', 'limpieza-del-hogar/detergentes-suavizantes', 1, 0),
    ('lavaplatos-desengrasantes', 'limpieza-del-hogar', 'Lavaplatos y Desengrasantes', 'Lavaplatos líquido y en pasta, limpiadores de cocina.', 'limpieza-del-hogar/lavaplatos-desengrasantes', 1, 1),
    ('limpiadores-desinfectantes', 'limpieza-del-hogar', 'Limpiadores y Desinfectantes', 'Multiusos, cloro, desinfectantes, limpiadores de baño y pisos.', 'limpieza-del-hogar/limpiadores-desinfectantes', 1, 2),
    ('papel-higienico-servilletas', 'limpieza-del-hogar', 'Papel Higiénico y Servilletas', 'Papel higiénico, toallas de papel, servilletas y pañuelos.', 'limpieza-del-hogar/papel-higienico-servilletas', 1, 3),
    ('utensilios-limpieza', 'limpieza-del-hogar', 'Utensilios de Limpieza', 'Escobas, trapeadores, esponjas, guantes y bolsas de basura.', 'limpieza-del-hogar/utensilios-limpieza', 1, 4),
    ('insecticidas-ambientadores', 'limpieza-del-hogar', 'Insecticidas y Ambientadores', 'Aromatizantes, insecticidas, repelentes y trampas.', 'limpieza-del-hogar/insecticidas-ambientadores', 1, 5),
    ('higiene-y-belleza', null, 'Higiene y Belleza', 'Cabello, piel, maquillaje, higiene y fragancias.', 'higiene-y-belleza', 0, 7),
    ('cuidado-del-cabello', 'higiene-y-belleza', 'Cuidado del Cabello', 'Shampoo, acondicionador, tintes, tratamientos y accesorios.', 'higiene-y-belleza/cuidado-del-cabello', 1, 0),
    ('cuidado-bucal', 'higiene-y-belleza', 'Cuidado Bucal', 'Cepillos, pastas, enjuagues e hilo dental.', 'higiene-y-belleza/cuidado-bucal', 1, 1),
    ('jabones-geles-bano', 'higiene-y-belleza', 'Jabones, Geles y Baño', 'Jabones, geles corporales, algodón e higiene personal.', 'higiene-y-belleza/jabones-geles-bano', 1, 2),
    ('desodorantes-antitranspirantes', 'higiene-y-belleza', 'Desodorantes y Antitranspirantes', 'Desodorantes y antitranspirantes.', 'higiene-y-belleza/desodorantes-antitranspirantes', 1, 3),
    ('cuidado-facial-corporal', 'higiene-y-belleza', 'Cuidado Facial y Corporal', 'Cremas, protección solar, tratamientos faciales y corporales.', 'higiene-y-belleza/cuidado-facial-corporal', 1, 4),
    ('afeitado-depilacion', 'higiene-y-belleza', 'Afeitado y Depilación', 'Rastrillos, cremas de afeitar y depilación.', 'higiene-y-belleza/afeitado-depilacion', 1, 5),
    ('higiene-femenina', 'higiene-y-belleza', 'Higiene Femenina', 'Toallas sanitarias, tampones y cuidado íntimo.', 'higiene-y-belleza/higiene-femenina', 1, 6),
    ('maquillaje-cosmetologia', 'higiene-y-belleza', 'Maquillaje y Cosmetología', 'Rostro, ojos, labios, uñas y accesorios cosméticos.', 'higiene-y-belleza/maquillaje-cosmetologia', 1, 7),
    ('fragancias', 'higiene-y-belleza', 'Fragancias', 'Perfumes y colonias.', 'higiene-y-belleza/fragancias', 1, 8),
    ('farmacia-y-salud', null, 'Farmacia y Salud', 'Medicamentos, vitaminas, equipo médico y primeros auxilios.', 'farmacia-y-salud', 0, 8),
    ('analgesicos-antiinflamatorios', 'farmacia-y-salud', 'Analgésicos y Antiinflamatorios', 'Dolor, fiebre, dolor muscular y de cabeza.', 'farmacia-y-salud/analgesicos-antiinflamatorios', 1, 0),
    ('gripe-tos-resfriado', 'farmacia-y-salud', 'Gripe, Tos y Resfriado', 'Antigripales, jarabes, alergias y sistema respiratorio.', 'farmacia-y-salud/gripe-tos-resfriado', 1, 1),
    ('salud-digestiva', 'farmacia-y-salud', 'Salud Digestiva', 'Antiácidos, antidiarreicos, laxantes y digestión.', 'farmacia-y-salud/salud-digestiva', 1, 2),
    ('medicamentos', 'farmacia-y-salud', 'Otros Medicamentos', 'Antibióticos, cardiovascular, diabetes, dermatológicos y tratamientos.', 'farmacia-y-salud/medicamentos', 1, 3),
    ('vitaminas-suplementos', 'farmacia-y-salud', 'Vitaminas y Suplementos', 'Vitaminas, minerales, colágeno, omega 3 y productos naturales.', 'farmacia-y-salud/vitaminas-suplementos', 1, 4),
    ('primeros-auxilios', 'farmacia-y-salud', 'Primeros Auxilios', 'Curitas, gasas, vendas, alcohol y antisépticos.', 'farmacia-y-salud/primeros-auxilios', 1, 5),
    ('equipo-medico', 'farmacia-y-salud', 'Equipo Médico y Ortopedia', 'Tensiómetros, glucómetros, nebulizadores, sillas de ruedas y soportes.', 'farmacia-y-salud/equipo-medico', 1, 6),
    ('salud-sexual', 'farmacia-y-salud', 'Salud Sexual', 'Preservativos, lubricantes y pruebas de embarazo.', 'farmacia-y-salud/salud-sexual', 1, 7),
    ('cuidado-adulto', 'farmacia-y-salud', 'Cuidado del Adulto', 'Pañales para adulto e incontinencia.', 'farmacia-y-salud/cuidado-adulto', 1, 8),
    ('bebes-y-ninos', null, 'Bebés y Niños', 'Pañales, alimentación, cuidado, ropa y paseo.', 'bebes-y-ninos', 0, 9),
    ('panales-toallitas-humedas', 'bebes-y-ninos', 'Pañales y Toallitas Húmedas', 'Pañales por etapa y toallitas húmedas.', 'bebes-y-ninos/panales-toallitas-humedas', 1, 0),
    ('alimentacion-infantil-formulas', 'bebes-y-ninos', 'Alimentación Infantil y Fórmulas', 'Fórmulas, colados, cereales y leches infantiles.', 'bebes-y-ninos/alimentacion-infantil-formulas', 1, 1),
    ('biberones-chupones-accesorios', 'bebes-y-ninos', 'Biberones, Chupones y Accesorios', 'Biberones, tetinas, lactancia y vajilla infantil.', 'bebes-y-ninos/biberones-chupones-accesorios', 1, 2),
    ('cuidado-higiene-bebe', 'bebes-y-ninos', 'Cuidado e Higiene del Bebé', 'Shampoo, cremas, baño e higiene del bebé.', 'bebes-y-ninos/cuidado-higiene-bebe', 1, 3),
    ('ropa-bebe', 'bebes-y-ninos', 'Ropa de Bebé', 'Conjuntos, pijamas, mamelucos y ropa interior de bebé.', 'bebes-y-ninos/ropa-bebe', 1, 4),
    ('puericultura-coches-sillas', 'bebes-y-ninos', 'Puericultura, Coches y Sillas', 'Coches, sillas de auto, cunas, corrales y sillas altas.', 'bebes-y-ninos/puericultura-coches-sillas', 1, 5),
    ('maternidad', 'bebes-y-ninos', 'Maternidad', 'Ropa para embarazadas, prenatal y accesorios de mamá.', 'bebes-y-ninos/maternidad', 1, 6),
    ('articulos-para-el-hogar', null, 'Artículos para el Hogar', 'Cocina, decoración, muebles, textiles, baño y jardín.', 'articulos-para-el-hogar', 0, 10),
    ('accesorios-para-cocina', 'articulos-para-el-hogar', 'Accesorios para Cocina', 'Ollas, sartenes, utensilios, recipientes y repostería.', 'articulos-para-el-hogar/accesorios-para-cocina', 1, 0),
    ('accesorios-mesa-vajillas', 'articulos-para-el-hogar', 'Accesorios para Mesa y Vajillas', 'Vajillas, cubiertos, vasos, cristalería y termos.', 'articulos-para-el-hogar/accesorios-mesa-vajillas', 1, 1),
    ('camas-colchones-blancos', 'articulos-para-el-hogar', 'Camas, Colchones y Blancos', 'Colchones, sábanas, edredones, almohadas y cobijas.', 'articulos-para-el-hogar/camas-colchones-blancos', 1, 2),
    ('textil-hogar', 'articulos-para-el-hogar', 'Textiles del Hogar', 'Toallas, manteles, cortinas y textil de cocina.', 'articulos-para-el-hogar/textil-hogar', 1, 3),
    ('decoracion-muebles', 'articulos-para-el-hogar', 'Decoración', 'Adornos, cuadros, velas, espejos, alfombras y plantas artificiales.', 'articulos-para-el-hogar/decoracion-muebles', 1, 4),
    ('muebles', 'articulos-para-el-hogar', 'Muebles', 'Salas, comedores, dormitorios, gabinetes y estantes.', 'articulos-para-el-hogar/muebles', 1, 5),
    ('bano', 'articulos-para-el-hogar', 'Baño', 'Accesorios, organizadores y textiles de baño.', 'articulos-para-el-hogar/bano', 1, 6),
    ('organizacion-almacenamiento', 'articulos-para-el-hogar', 'Organización y Almacenamiento', 'Cajas, canastas, organizadores, ganchos y perchas.', 'articulos-para-el-hogar/organizacion-almacenamiento', 1, 7),
    ('desechables', 'articulos-para-el-hogar', 'Desechables', 'Platos, vasos, cubiertos, bolsas y envoltorios desechables.', 'articulos-para-el-hogar/desechables', 1, 8),
    ('fiestas', 'articulos-para-el-hogar', 'Fiestas y Regalos', 'Artículos de fiesta, piñatería, envolturas y disfraces.', 'articulos-para-el-hogar/fiestas', 1, 9),
    ('iluminacion', 'articulos-para-el-hogar', 'Iluminación', 'Lámparas, focos, tiras LED y linternas.', 'articulos-para-el-hogar/iluminacion', 1, 10),
    ('jardin-exteriores', 'articulos-para-el-hogar', 'Jardín y Exteriores', 'Muebles de jardín, macetas, piscinas, asadores y herramientas de jardín.', 'articulos-para-el-hogar/jardin-exteriores', 1, 11),
    ('electrodomesticos', null, 'Electrodomésticos', 'Línea blanca y pequeños electrodomésticos.', 'electrodomesticos', 0, 11),
    ('refrigeracion', 'electrodomesticos', 'Refrigeradoras y Congeladores', 'Refrigeradoras, freezers, dispensadores de agua y vineras.', 'electrodomesticos/refrigeracion', 1, 0),
    ('lavado-secado', 'electrodomesticos', 'Lavadoras y Secadoras', 'Lavadoras, secadoras, centros de lavado y planchas.', 'electrodomesticos/lavado-secado', 1, 1),
    ('estufas-hornos', 'electrodomesticos', 'Estufas y Hornos', 'Estufas, hornos, cooktops, campanas y lavavajillas.', 'electrodomesticos/estufas-hornos', 1, 2),
    ('climatizacion', 'electrodomesticos', 'Aires y Ventiladores', 'Aires acondicionados, ventiladores, calentadores y humidificadores.', 'electrodomesticos/climatizacion', 1, 3),
    ('electrodomesticos-cocina', 'electrodomesticos', 'Electrodomésticos de Cocina', 'Licuadoras, cafeteras, freidoras, microondas, tostadoras y batidoras.', 'electrodomesticos/electrodomesticos-cocina', 1, 4),
    ('aspiradoras', 'electrodomesticos', 'Aspiradoras y Cuidado de Pisos', 'Aspiradoras, hidrolavadoras y limpieza de pisos.', 'electrodomesticos/aspiradoras', 1, 5),
    ('cuidado-personal-electrico', 'electrodomesticos', 'Cuidado Personal Eléctrico', 'Secadoras, planchas de cabello, afeitadoras, masajeadores y cepillos eléctricos.', 'electrodomesticos/cuidado-personal-electrico', 1, 6),
    ('tecnologia', null, 'Tecnología', 'Celulares, computación, audio, video, gaming y redes.', 'tecnologia', 0, 12),
    ('telefonos-celulares', 'tecnologia', 'Teléfonos y Celulares', 'Smartphones y teléfonos.', 'tecnologia/telefonos-celulares', 1, 0),
    ('accesorios-celular', 'tecnologia', 'Accesorios para Celular', 'Fundas, cargadores, cables, power banks y soportes.', 'tecnologia/accesorios-celular', 1, 1),
    ('tablets', 'tecnologia', 'Tablets', 'Tablets y accesorios.', 'tecnologia/tablets', 1, 2),
    ('computadoras', 'tecnologia', 'Computadoras', 'Laptops, computadoras de escritorio y all-in-one.', 'tecnologia/computadoras', 1, 3),
    ('componentes-pc', 'tecnologia', 'Componentes de PC', 'Procesadores, memorias RAM, placas madre, tarjetas gráficas, fuentes y refrigeración.', 'tecnologia/componentes-pc', 1, 4),
    ('perifericos', 'tecnologia', 'Periféricos y Monitores', 'Mouse, teclados, monitores, cámaras web y mouse pads.', 'tecnologia/perifericos', 1, 5),
    ('almacenamiento-datos', 'tecnologia', 'Almacenamiento de Datos', 'Discos duros, SSD, memorias USB y tarjetas SD.', 'tecnologia/almacenamiento-datos', 1, 6),
    ('impresoras', 'tecnologia', 'Impresoras y Consumibles', 'Impresoras, multifuncionales, escáneres, tintas y tóner.', 'tecnologia/impresoras', 1, 7),
    ('redes', 'tecnologia', 'Redes y Conectividad', 'Routers, repetidores, switches y cables de red.', 'tecnologia/redes', 1, 8),
    ('audio', 'tecnologia', 'Audio', 'Audífonos, parlantes, barras de sonido y equipos de sonido.', 'tecnologia/audio', 1, 9),
    ('tv-video', 'tecnologia', 'TV y Video', 'Televisores, proyectores, soportes, streaming y controles.', 'tecnologia/tv-video', 1, 10),
    ('videojuegos', 'tecnologia', 'Videojuegos', 'Juegos y accesorios gaming.', 'tecnologia/videojuegos', 1, 11),
    ('consolas-de-videojuegos', 'tecnologia', 'Consolas de Videojuegos', 'Consolas y controles.', 'tecnologia/consolas-de-videojuegos', 1, 12),
    ('playstation', 'tecnologia', 'PlayStation', 'Consolas, juegos y accesorios PlayStation.', 'tecnologia/playstation', 1, 13),
    ('xbox', 'tecnologia', 'Xbox', 'Consolas, juegos y accesorios Xbox.', 'tecnologia/xbox', 1, 14),
    ('nintendo', 'tecnologia', 'Nintendo', 'Consolas, juegos y accesorios Nintendo.', 'tecnologia/nintendo', 1, 15),
    ('codigos-digitales', 'tecnologia', 'Códigos Digitales', 'Tarjetas y códigos de recarga y contenido digital.', 'tecnologia/codigos-digitales', 1, 16),
    ('camaras-drones', 'tecnologia', 'Cámaras y Drones', 'Cámaras, drones, acción y accesorios de foto.', 'tecnologia/camaras-drones', 1, 17),
    ('bandas-actividad-y-smartwatches', 'tecnologia', 'Bandas de Actividad y Smartwatches', 'Relojes inteligentes y bandas de actividad.', 'tecnologia/bandas-actividad-y-smartwatches', 1, 18),
    ('hogar-inteligente', 'tecnologia', 'Hogar Inteligente', 'Focos, enchufes, asistentes y dispositivos smart home.', 'tecnologia/hogar-inteligente', 1, 19),
    ('seguridad-vigilancia', 'tecnologia', 'Seguridad y Vigilancia', 'Cámaras de seguridad, DVR, alarmas, timbres y control de acceso.', 'tecnologia/seguridad-vigilancia', 1, 20),
    ('energia-respaldo', 'tecnologia', 'Energía y Respaldo', 'UPS, reguladores, protectores de voltaje y energía solar.', 'tecnologia/energia-respaldo', 1, 21),
    ('cables-adaptadores', 'tecnologia', 'Cables y Adaptadores', 'HDMI, USB, adaptadores, hubs y conectores de audio y video.', 'tecnologia/cables-adaptadores', 1, 22),
    ('componentes-electronicos', 'tecnologia', 'Electrónica y Proyectos', 'Componentes, protoboards, placas de desarrollo, sensores y módulos.', 'tecnologia/componentes-electronicos', 1, 23),
    ('software', 'tecnologia', 'Software', 'Antivirus, licencias y programas.', 'tecnologia/software', 1, 24),
    ('radios-comunicacion', 'tecnologia', 'Radios y Comunicación', 'Radios de dos vías, intercomunicadores y antenas.', 'tecnologia/radios-comunicacion', 1, 25),
    ('instrumentos-musicales', 'tecnologia', 'Instrumentos Musicales', 'Instrumentos y equipo para músicos.', 'tecnologia/instrumentos-musicales', 1, 26),
    ('jugueteria-y-juegos', null, 'Juguetería y Juegos', 'Juguetes y juegos para todas las edades.', 'jugueteria-y-juegos', 0, 13),
    ('juguetes-bebes-estimulacion', 'jugueteria-y-juegos', 'Juguetes de Bebés y Estimulación', 'Juguetes de bebé, sonajeros y estimulación temprana.', 'jugueteria-y-juegos/juguetes-bebes-estimulacion', 1, 0),
    ('juguetes-educativos', 'jugueteria-y-juegos', 'Juguetes Educativos', 'Didácticos, Montessori, ciencia y aprendizaje.', 'jugueteria-y-juegos/juguetes-educativos', 1, 1),
    ('munecas-figuras-vehiculos', 'jugueteria-y-juegos', 'Muñecas, Figuras y Vehículos', 'Muñecas, peluches, figuras de acción, carritos y pistas.', 'jugueteria-y-juegos/munecas-figuras-vehiculos', 1, 2),
    ('coleccionables-tcg', 'jugueteria-y-juegos', 'Coleccionables y TCG', 'Cartas coleccionables, álbumes, minifiguras y coleccionables.', 'jugueteria-y-juegos/coleccionables-tcg', 1, 3),
    ('bloques-construccion', 'jugueteria-y-juegos', 'Bloques y Construcción', 'LEGO, bloques y sets para armar.', 'jugueteria-y-juegos/bloques-construccion', 1, 4),
    ('juegos-de-mesa-rompecabezas', 'jugueteria-y-juegos', 'Juegos de Mesa y Rompecabezas', 'Juegos familiares, cartas y rompecabezas.', 'jugueteria-y-juegos/juegos-de-mesa-rompecabezas', 1, 5),
    ('juguetes-exterior-aire-libre', 'jugueteria-y-juegos', 'Juguetes Exterior y Aire Libre', 'Juguetes de exterior, montables, triciclos y patinetas.', 'jugueteria-y-juegos/juguetes-exterior-aire-libre', 1, 6),
    ('juegos-imitacion', 'jugueteria-y-juegos', 'Imitación y Roles', 'Cocinitas, casitas y sets de juego.', 'jugueteria-y-juegos/juegos-imitacion', 1, 7),
    ('ferreteria', null, 'Ferretería y Construcción', 'Herramientas, electricidad, plomería, pintura y materiales.', 'ferreteria', 0, 14),
    ('herramientas-manuales', 'ferreteria', 'Herramientas Manuales', 'Martillos, desarmadores, llaves, alicates y juegos de herramientas.', 'ferreteria/herramientas-manuales', 1, 0),
    ('herramientas-electricas', 'ferreteria', 'Herramientas Eléctricas', 'Taladros, sierras, lijadoras, esmeriles y accesorios.', 'ferreteria/herramientas-electricas', 1, 1),
    ('electricidad', 'ferreteria', 'Electricidad', 'Cable eléctrico, breakers, interruptores, tomas, extensiones y pilas.', 'ferreteria/electricidad', 1, 2),
    ('plomeria', 'ferreteria', 'Plomería', 'Tubería, grifos, válvulas, inodoros, lavamanos y bombas de agua.', 'ferreteria/plomeria', 1, 3),
    ('materiales-construccion', 'ferreteria', 'Materiales de Construcción', 'Cemento, varilla, láminas, pisos, azulejos, puertas y ventanas.', 'ferreteria/materiales-construccion', 1, 4),
    ('pintura-brochas', 'ferreteria', 'Pintura y Brochas', 'Pinturas, brochas, rodillos, selladores y solventes.', 'ferreteria/pintura-brochas', 1, 5),
    ('fijacion-herrajes', 'ferreteria', 'Fijación y Herrajes', 'Tornillos, clavos, anclajes, bisagras, candados y cerraduras.', 'ferreteria/fijacion-herrajes', 1, 6),
    ('seguridad-industrial', 'ferreteria', 'Seguridad Industrial', 'Guantes, calzado de seguridad, protección personal y extintores.', 'ferreteria/seguridad-industrial', 1, 7),
    ('soldadura', 'ferreteria', 'Soldadura y Gas', 'Soldadoras, electrodos, sopletes y cilindros de gas.', 'ferreteria/soldadura', 1, 8),
    ('medicion', 'ferreteria', 'Medición y Trazado', 'Cintas métricas, niveles, multímetros y escuadras.', 'ferreteria/medicion', 1, 9),
    ('maquinaria', 'ferreteria', 'Maquinaria y Equipo', 'Compresores, generadores, motores, hidrolavadoras y bombas.', 'ferreteria/maquinaria', 1, 10),
    ('almacenamiento-taller', 'ferreteria', 'Almacenamiento y Taller', 'Cajas de herramientas, gabinetes, estanterías y escaleras.', 'ferreteria/almacenamiento-taller', 1, 11),
    ('automotriz', null, 'Automotriz', 'Accesorios, repuestos y mantenimiento para vehículos.', 'automotriz', 0, 15),
    ('accesorios-cuidado-autos', 'automotriz', 'Accesorios y Cuidado para Autos', 'Tapetes, fundas, organizadores, soportes y limpieza.', 'automotriz/accesorios-cuidado-autos', 1, 0),
    ('repuestos-y-mantenimiento', 'automotriz', 'Repuestos y Mantenimiento', 'Aceites, baterías, fusibles, llantas y herramientas de mecánica.', 'automotriz/repuestos-y-mantenimiento', 1, 1),
    ('audio-auto', 'automotriz', 'Audio y Electrónica para Auto', 'Audio, cargadores, inversores y transmisores para vehículo.', 'automotriz/audio-auto', 1, 2),
    ('motos-y-cuatrimotos', 'automotriz', 'Motos y Cuatrimotos', 'Motos, cuatrimotos, mototaxis y scooters eléctricos.', 'automotriz/motos-y-cuatrimotos', 1, 3),
    ('mascotas', null, 'Mascotas', 'Alimento y accesorios para perros, gatos y otras mascotas.', 'mascotas', 0, 16),
    ('alimento-para-perros', 'mascotas', 'Alimento para Perros', 'Alimento seco, húmedo y snacks para perros.', 'mascotas/alimento-para-perros', 1, 0),
    ('alimento-para-gatos', 'mascotas', 'Alimento para Gatos', 'Alimento seco, húmedo y arena para gatos.', 'mascotas/alimento-para-gatos', 1, 1),
    ('otras-mascotas', 'mascotas', 'Otras Mascotas', 'Aves, peces, conejos, tortugas y roedores.', 'mascotas/otras-mascotas', 1, 2),
    ('juguetes-accesorios-mascotas', 'mascotas', 'Juguetes y Accesorios para Mascotas', 'Camas, correas, collares, comederos y juguetes.', 'mascotas/juguetes-accesorios-mascotas', 1, 3),
    ('higiene-cuidado-mascotas', 'mascotas', 'Higiene y Cuidado de Mascotas', 'Shampoo, antiparasitarios, salud y grooming.', 'mascotas/higiene-cuidado-mascotas', 1, 4),
    ('libreria-y-papelera', null, 'Librería y Papelería', 'Escritura, papel, útiles, arte, libros y muebles de oficina.', 'libreria-y-papelera', 0, 17),
    ('escritura-correccion', 'libreria-y-papelera', 'Escritura y Corrección', 'Bolígrafos, lápices, marcadores, resaltadores y correctores.', 'libreria-y-papelera/escritura-correccion', 1, 0),
    ('cuadernos-libretas-hojas', 'libreria-y-papelera', 'Cuadernos, Libretas y Hojas', 'Cuadernos, libretas, papel, cartulinas y agendas.', 'libreria-y-papelera/cuadernos-libretas-hojas', 1, 1),
    ('archivo', 'libreria-y-papelera', 'Archivo y Organización', 'Folders, archivadores, binders, sobres y separadores.', 'libreria-y-papelera/archivo', 1, 2),
    ('utiles-escolares-oficina', 'libreria-y-papelera', 'Útiles Escolares y de Oficina', 'Mochilas, loncheras, kits, tijeras, engrapadoras y calculadoras.', 'libreria-y-papelera/utiles-escolares-oficina', 1, 3),
    ('arte-manualidades', 'libreria-y-papelera', 'Arte y Manualidades', 'Pinturas, pinceles, lienzos, plastilina y materiales creativos.', 'libreria-y-papelera/arte-manualidades', 1, 4),
    ('muebles-oficina', 'libreria-y-papelera', 'Muebles de Oficina', 'Escritorios, sillas de oficina y gaming.', 'libreria-y-papelera/muebles-oficina', 1, 5),
    ('libros', 'libreria-y-papelera', 'Libros y Revistas', 'Libros, cuentos, manga, diccionarios y textos.', 'libreria-y-papelera/libros', 1, 6),
    ('ropa-y-moda', null, 'Ropa y Moda', 'Ropa para mujer, hombre y niños.', 'ropa-y-moda', 0, 18),
    ('ropa-femenina', 'ropa-y-moda', 'Ropa Femenina', 'Blusas, pantalones, vestidos y ropa de mujer.', 'ropa-y-moda/ropa-femenina', 1, 0),
    ('ropa-masculina', 'ropa-y-moda', 'Ropa Masculina', 'Camisas, pantalones, jeans y ropa de hombre.', 'ropa-y-moda/ropa-masculina', 1, 1),
    ('ropa-infantil', 'ropa-y-moda', 'Ropa Infantil', 'Ropa de niños y niñas.', 'ropa-y-moda/ropa-infantil', 1, 2),
    ('ropa-deportiva', 'ropa-y-moda', 'Ropa Deportiva', 'Ropa y calzado deportivo, camisetas de fútbol.', 'ropa-y-moda/ropa-deportiva', 1, 3),
    ('ropa-interior-y-pijamas', 'ropa-y-moda', 'Ropa Interior y Pijamas', 'Ropa interior, pijamas, medias y calcetines.', 'ropa-y-moda/ropa-interior-y-pijamas', 1, 4),
    ('trajes-de-bano', 'ropa-y-moda', 'Trajes de Baño', 'Trajes de baño y playa.', 'ropa-y-moda/trajes-de-bano', 1, 5),
    ('basicos-y-algodon', 'ropa-y-moda', 'Básicos y Algodón', 'Básicos de algodón y camisetas.', 'ropa-y-moda/basicos-y-algodon', 1, 6),
    ('calzado', null, 'Calzado', 'Zapatos, tenis y pantuflas.', 'calzado', 0, 19),
    ('calzado-masculino', 'calzado', 'Calzado Masculino', 'Zapatos y pantuflas de hombre.', 'calzado/calzado-masculino', 1, 0),
    ('calzado-femenino', 'calzado', 'Calzado Femenino', 'Zapatos y sandalias de mujer.', 'calzado/calzado-femenino', 1, 1),
    ('calzado-infantil', 'calzado', 'Calzado Infantil', 'Zapatos de niños y niñas.', 'calzado/calzado-infantil', 1, 2),
    ('tenis-y-deportivo', 'calzado', 'Tenis y Deportivo', 'Tenis y calzado deportivo.', 'calzado/tenis-y-deportivo', 1, 3),
    ('accesorios-de-moda', null, 'Accesorios de Moda', 'Carteras, relojes, gorras, lentes, joyería y sombreros.', 'accesorios-de-moda', 0, 20),
    ('bolsos-mochilas-y-billeteras', 'accesorios-de-moda', 'Bolsos, Mochilas y Billeteras', 'Carteras, bolsos y billeteras.', 'accesorios-de-moda/bolsos-mochilas-y-billeteras', 1, 0),
    ('relojes-y-joyeria', 'accesorios-de-moda', 'Relojes y Joyería', 'Relojes y joyería.', 'accesorios-de-moda/relojes-y-joyeria', 1, 1),
    ('lentes-y-gorras', 'accesorios-de-moda', 'Lentes y Gorras', 'Lentes de sol, de lectura, gorras y sombreros.', 'accesorios-de-moda/lentes-y-gorras', 1, 2),
    ('deportes-y-fitness', null, 'Deportes y Fitness', 'Ejercicio, deportes, ciclismo y camping.', 'deportes-y-fitness', 0, 21),
    ('maquinas-cardio-gimnasio', 'deportes-y-fitness', 'Máquinas de Cardio y Gimnasio', 'Caminadoras, elípticas, bicicletas fijas y máquinas de ejercicio.', 'deportes-y-fitness/maquinas-cardio-gimnasio', 1, 0),
    ('pesas-y-equipos-de-fuerza', 'deportes-y-fitness', 'Pesas y Equipos de Fuerza', 'Mancuernas, pesas, barras y equipo de fuerza.', 'deportes-y-fitness/pesas-y-equipos-de-fuerza', 1, 1),
    ('accesorios-fitness-y-ejercicio', 'deportes-y-fitness', 'Accesorios Fitness y Ejercicio', 'Colchonetas, bandas, yoga y accesorios de entrenamiento.', 'deportes-y-fitness/accesorios-fitness-y-ejercicio', 1, 2),
    ('disciplinas-deportivas', 'deportes-y-fitness', 'Disciplinas Deportivas', 'Fútbol, básquet, volleyball, boxeo, tenis, natación y más.', 'deportes-y-fitness/disciplinas-deportivas', 1, 3),
    ('ciclismo-y-bicicletas', 'deportes-y-fitness', 'Ciclismo y Bicicletas', 'Bicicletas, scooters y accesorios.', 'deportes-y-fitness/ciclismo-y-bicicletas', 1, 4),
    ('camping', 'deportes-y-fitness', 'Camping y Aire Libre', 'Carpas, hieleras, pesca y equipo de campamento.', 'deportes-y-fitness/camping', 1, 5),
    ('nutricion-deportiva', 'deportes-y-fitness', 'Nutrición Deportiva', 'Proteínas, creatina y suplementos deportivos.', 'deportes-y-fitness/nutricion-deportiva', 1, 6),
    ('equipaje-y-viaje', null, 'Equipaje y Viaje', 'Maletas, maletines y kits de viaje.', 'equipaje-y-viaje', 0, 22),
    ('maletas-y-equipaje', 'equipaje-y-viaje', 'Maletas y Equipaje', 'Maletas, sets de equipaje y kits de viaje.', 'equipaje-y-viaje/maletas-y-equipaje', 1, 0),
    ('bolsos-deportivos-y-maletines', 'equipaje-y-viaje', 'Bolsos Deportivos y Maletines', 'Maletines, bolsos deportivos y mochilas de viaje.', 'equipaje-y-viaje/bolsos-deportivos-y-maletines', 1, 1),
    ('de-temporada', null, 'De Temporada', 'Navidad, Halloween, liquidación y curiosidades.', 'de-temporada', 0, 23),
    ('navidad', 'de-temporada', 'Navidad', 'Árboles, adornos, luces y decoración navideña.', 'de-temporada/navidad', 1, 0),
    ('halloween', 'de-temporada', 'Halloween', 'Decoración y dulces de Halloween.', 'de-temporada/halloween', 1, 1),
    ('liquidacion', 'de-temporada', 'Liquidación', 'Outlet, remates y liquidación.', 'de-temporada/liquidacion', 1, 2),
    ('curiosidades', 'de-temporada', 'Curiosidades', 'Curiosidades, gadgets y regalos.', 'de-temporada/curiosidades', 1, 3),
    ('publicidad-y-comercio', null, 'Publicidad y Comercio', 'Rotulación, promocionales y punto de venta.', 'publicidad-y-comercio', 0, 24),
    ('rotulacion-y-exhibicion', 'publicidad-y-comercio', 'Rotulación y Exhibición', 'Rótulos, soportes publicitarios y exhibición.', 'publicidad-y-comercio/rotulacion-y-exhibicion', 1, 0),
    ('articulos-promocionales-e-impulso', 'publicidad-y-comercio', 'Artículos Promocionales e Impulso', 'Promocionales y productos de impulso.', 'publicidad-y-comercio/articulos-promocionales-e-impulso', 1, 1),
    ('punto-de-venta', 'publicidad-y-comercio', 'Punto de Venta', 'Impresoras POS, lectores de código, básculas y contadoras de billetes.', 'publicidad-y-comercio/punto-de-venta', 1, 2)
),
roots as (
  insert into find_your_prices.categories (slug, parent_id, name, description, path, level, position)
  select slug, null, name, description, path, level, position
  from nodes where parent_slug is null
  on conflict (slug) do update set
    parent_id   = null,
    name        = excluded.name,
    description = excluded.description,
    path        = excluded.path,
    level       = excluded.level,
    position    = excluded.position,
    is_active   = true
  returning id, slug
)
insert into find_your_prices.categories (slug, parent_id, name, description, path, level, position)
select n.slug, r.id, n.name, n.description, n.path, n.level, n.position
from nodes n
join roots r on r.slug = n.parent_slug
on conflict (slug) do update set
  parent_id   = excluded.parent_id,
  name        = excluded.name,
  description = excluded.description,
  path        = excluded.path,
  level       = excluded.level,
  position    = excluded.position,
  is_active   = true;

-- Reporte: cuántos nodos quedaron por nivel.
select level, count(*) as nodos
from find_your_prices.categories
group by level order by level;
