// Static product fixture used across the app until a real data source is
// wired up. Pure data, no side effects.

import type { Product } from "@/types";
import { DEFAULT_CURRENCY } from "@/lib/constants";

export const products: Product[] = [
  {
    id: "prod-001",
    name: "Wireless Mouse",
    price: 24.99,
    currency: DEFAULT_CURRENCY,
    store: "Amazon",
    category: "Electronics",
    imageUrl: "/images/wireless-mouse.jpg",
    availability: "In stock",
    description: "Ergonomic wireless mouse with adjustable DPI settings.",
  },
  {
    id: "prod-002",
    name: "Mechanical Keyboard",
    price: 89.99,
    currency: DEFAULT_CURRENCY,
    store: "Amazon",
    category: "Electronics",
    imageUrl: "/images/mechanical-keyboard.jpg",
    availability: "In stock",
    description: "Tactile mechanical keyboard with RGB backlighting.",
  },
  {
    id: "prod-003",
    name: "Stainless Steel Blender",
    price: 59.5,
    currency: DEFAULT_CURRENCY,
    store: "Walmart",
    category: "Home",
    imageUrl: "/images/blender.jpg",
    availability: "In stock",
    description: "High-power blender for smoothies and soups.",
  },
  {
    id: "prod-004",
    name: "Air Fryer",
    price: 79.0,
    currency: DEFAULT_CURRENCY,
    store: "Walmart",
    category: "Home",
    availability: "Out of stock",
    description: "Compact air fryer with digital temperature control.",
  },
  {
    id: "prod-005",
    name: "Running Shoes",
    price: 64.95,
    currency: DEFAULT_CURRENCY,
    store: "Target",
    category: "Apparel",
    imageUrl: "/images/running-shoes.jpg",
    description: "Lightweight running shoes with breathable mesh upper.",
  },
  {
    id: "prod-006",
    name: "Yoga Mat",
    price: 19.99,
    currency: DEFAULT_CURRENCY,
    store: "Target",
    category: "Apparel",
    imageUrl: "/images/yoga-mat.jpg",
    availability: "In stock",
  },
  {
    id: "prod-007",
    name: "Bluetooth Headphones",
    price: 129.99,
    currency: DEFAULT_CURRENCY,
    store: "Best Buy",
    category: "Electronics",
    imageUrl: "/images/bluetooth-headphones.jpg",
    availability: "In stock",
    description: "Over-ear headphones with active noise cancellation.",
  },
  {
    id: "prod-008",
    name: "Coffee Maker",
    price: 45.0,
    currency: DEFAULT_CURRENCY,
    store: "Best Buy",
    category: "Home",
    availability: "In stock",
  },
];
